### ISSUE TITLE
Capable for winxp

### ISSUE THREAD

**Issue by wyf180** [JHRobotics/wine9x#1]
I tried to replace d3d files with this wined3d to winxp.However it crashed when testing d3d7.However 3d winxp screensaver need dx8 support could work.So I think some bugs   must be fixed for xp.

**Comment by Torinde** [comment]
Seems that [got implemented](https://github.com/JHRobotics/wine9x?tab=readme-ov-file#windows-xp)?

Related:
- https://github.com/JHRobotics/softgpu/issues/12

**Comment by mirh** [comment]
https://fdossena.com/?p=wined3d/index.frag
